### ISSUE TITLE
Add tag link

### ISSUE THREAD

**Issue by HarelM** [JOSM/tag2link#9]
Hi, 

I got a message in the following form about tag links:
https://community.openstreetmap.org/t/bulk-edit-announcement-addition-of-inature-reference/117181/9

I would basically like to add a tag link from osm to inature.info using ref:IL:inature tag.
How can I do that? I haven't found good instructions in the readme or the linked site.
Do I open a PR? Do I edit an OSM wiki page somewhere? 

Thanks!!

**Comment by tsmock** [comment]
1. Read https://wiki.openstreetmap.org/wiki/Data_items
2. Create the item (see https://wiki.openstreetmap.org/wiki/Data_items#Item_creation_process )
3. Input the standard information for the tag. Be as complete as possible please.
4. Add the `formatter url` (`P8`) property

Example: https://wiki.openstreetmap.org/wiki/Item:Q401

**Comment by HarelM** [comment]
Sorry for commenting on a closed issue, but I would appreciate a review on the item I created in the following link:
https://wiki.openstreetmap.org/wiki/Item:Q22610
Let me know if I missed anything and how will this be seen and where in term od iD or somewhere else.

**Comment by HarelM** [comment]
P.S. I think the above information can be really helpful in either the readme of this repo or a contribution guide.
The above links and mapillary example were very helpful, thanks!

**Comment by tsmock** [comment]
1. The entry as it was _is_ usable by this script
2. A few other things should have been done for other consumers. Specifically, the _site link_ from the linked item creation process was skipped. I've fixed it.
3. There were a couple of other fixes I did. If you want to see them, look at the history.

I'll go ahead and add contribution instructions to the readme.

**Comment by HarelM** [comment]
Thanks!
